version: '3.3'

networks:
  # network to keep postgres database isolated
  dbnetwork:

configs:
  esg-trust-bundle:
    file: $ESGF_CONFIG/certificates/esg-trust-bundle.pem
  # FIXME
  nginx-conf:
    file: /Users/cinquini/eclipse-workspace/esgf-docker/esgf.conf
  tomcat-conf:
    file: /Users/cinquini/eclipse-workspace/esgf-docker/server.xml

secrets:
  database-password:
    file: $ESGF_CONFIG/secrets/database-password
  database-publisher-password:
    file: $ESGF_CONFIG/secrets/database-publisher-password
  rootadmin-password:
    file: $ESGF_CONFIG/secrets/rootadmin-password
  hostcert:
    file: $ESGF_CONFIG/certificates/hostcert/hostcert.crt
  hostkey: 
    file: $ESGF_CONFIG/certificates/hostcert/hostcert.key
  shared-cookie-secret-key:
    file: $ESGF_CONFIG/secrets/shared-cookie-secret-key

services:

  # ESGF postgres database
  esgf-postgres:
    image: "${ESGF_HUB}/esgf-postgres:${ESGF_VERSION}"
    networks:
      - dbnetwork
    environment:
      DBSUPER_PASSWORD_FILE: /esg/secrets/database-password
      ESGCET_PASSWORD_FILE: /esg/secrets/database-publisher-password
      ESGF_ROOTADMIN_EMAIL: "CoG@${ESGF_HOSTNAME}"
      ESGF_ROOTADMIN_USERNAME: rootAdmin
      ESGF_ROOTADMIN_OPENID: https://${ESGF_HOSTNAME}/esgf-idp/openid/rootAdmin
      ESGF_ROOTADMIN_PASSWORD_FILE: /esg/secrets/rootadmin-password
    secrets:
      - source: database-password
        target: /esg/secrets/database-password
      - source: database-publisher-password
        target: /esg/secrets/database-publisher-password
      - source: rootadmin-password
        target: /esg/secrets/rootadmin-password
    volumes:
      - pg_data:/var/lib/pgsql/data
    deploy:
      placement:
        constraints: [node.labels.esgf_db_node == true]
      
  # ESGF Identity Provider  
  esgf-idp-node:
    image: "${ESGF_HUB}/esgf-idp-node:${ESGF_VERSION}"
    networks:
      - default
      - dbnetwork
    ports:
      - "8081:8080"
    environment: 
      ESGF_HOSTNAME:
      ESGF_DATABASE_HOST: esgf-postgres
    secrets:
    - source: database-password
      target: /esg/config/.esg_pg_pass
    configs:
      - source: esg-trust-bundle
        target: /esg/certificates/esg-trust-bundle.pem 
    depends_on:
      - esgf-postgres
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.esgf_idp_node == true]
        
  # TDS 
  esgf-tds:
    image: "${ESGF_HUB}/esgf-tds:${ESGF_VERSION}"
    ports:
      - "8082:8080"
    environment:
      ESGF_HOSTNAME:
      ESGF_DATABASE_HOST: esgf-postgres
      ESGF_COOKIE_SECRET_KEY_FILE: /esg/secrets/shared-cookie-secret-key
      ESGF_TDS_ADMIN_PASSWORD_FILE: /esg/secrets/rootadmin-password
    volumes:
      - "tds_content:/esg/content/thredds"
      - "esg_data:/esg/data"
    secrets:
      - source: rootadmin-password
        target: /esg/secrets/rootadmin-password
      - source: shared-cookie-secret-key
        target: /esg/secrets/shared-cookie-secret-key
    configs: 
      - source: esg-trust-bundle
        target: /esg/certificates/esg-trust-bundle.pem 
    depends_on:
      - esgf-postgres
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.esgf_data_node == true]
    
        
  # ESGF proxy
#  esgf-proxy:
#    image: "${ESGF_HUB}/esgf-proxy:${ESGF_VERSION}"
#    networks: 
#      - default
#    ports:
#      - "80:80"
#      - "443:443"
#    environment: 
#      ESGF_HOSTNAME:
#      ESGF_SOLR_UPSTREAM: http://esgf-solr:8983
#      ESGF_INDEX_NODE_UPSTREAM: http://esgf-index-node:8080
#      ESGF_TDS_UPSTREAM: http://esgf-tds:8080
#      ESGF_COG_UPSTREAM: http://esgf-cog:8000
#      ESGF_ORP_UPSTREAM: http://esgf-orp:8080
#      ESGF_IDP_UPSTREAM: http://esgf-idp-node:8080
#      ESGF_SLCS_UPSTREAM: http://esgf-slcs:8000
#      ESGF_AUTH_UPSTREAM: http://esgf-auth:8000
#    secrets:
#    - source: hostcert
#      target: /etc/nginx/ssl/hostcert.crt
#    - source: hostkey
#      target: /etc/nginx/ssl/hostcert.key
#    configs:
#      - source: esg-trust-bundle
#        target: /esg/certificates/esg-trust-bundle.pem 
#      # FIXME
#      - source: nginx-conf
#        target: /etc/nginx/conf.d/esgf.conf
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.labels.esgf_front_node == true]


# Use Docker volumes to store persistent data
volumes:
  # postgres database
  pg_data:
  # TDS catalogs
  tds_content:
  # science data
  esg_data: 